version: '3.7'

services:
  # backend api
  smart-brain-api:
    container_name: backend
    build:  ./
    command:  npm start
    working_dir:  /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://phantom:secret@postgres:5432/smart-brain-docker
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
  # postgres
  postgres:
    environment:
      POSTGRES_USER: phantom
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build:  ./postgres
    ports:
      - "5433:5432"
